// Mocks generated by Mockito 5.0.16 from annotations
// in tip/test/usecases/expenses.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tip/src/features/expanses/domain/entities.dart' as _i4;
import 'package:tip/src/features/expanses/domain/repositories.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [BudgetTransactionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetTransactionsRepository extends _i1.Mock
    implements _i2.BudgetTransactionsRepository {
  MockBudgetTransactionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BudgetTransactions>> getByPreviousMonth(
          {int? fromToday}) =>
      (super.noSuchMethod(
          Invocation.method(#getByPreviousMonth, [], {#fromToday: fromToday}),
          returnValue: Future<List<_i4.BudgetTransactions>>.value(
              <_i4.BudgetTransactions>[])) as _i3
          .Future<List<_i4.BudgetTransactions>>);
  @override
  String toString() => super.toString();
}
